Derive Stackheights via extended GNFR Mapping File
UBA-DE-Emissionsituation/eprtr2lps pull request #20
Opened 2021-04-05 14:12 UTC by Christian-Mielke

Here I have modified the ipybn a bit after your template @AnnaZagorski @kevin-hausmann  together with a new gnfr mapping table which includes the stackheights now. Stackheights dense means: All stackheights that are above 90% of the researched stackheights according to UBA report No 3717 51 1010. Stackheights sparse means exluding all stackheights which are not follwoing the report table Pages 181-186 to the letter.

2021-04-06 16:23 UTC, kevin-hausmann requested changes
This is a good start! Please note my detailed feedback inline. Not that you can simply push to the branch to update the pull request...

2021-04-06 16:23 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "        chimney_mapping[line[0]]= line[4]#set to three for height class set to 4 for meters\n",
While it is good to have both, please make sure to use the stack height classes for the actual preparation of the data, as those are the expected values for the template, please change this here.

2021-04-06 16:23 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +  {
Please remove empty cells

2021-04-06 16:23 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +   "version": "3.8.5"
Please do not commit these environment dependent changes.

2021-04-06 16:23 UTC, kevin-hausmann commented on data/gnfr_mapping.csv
> +1.b;Installations for gasification and liquefaction;B_Industry;;;;
This is incomplete and it also shows in the output.csv. Many stack heights values are empty. How do we fix this?

2021-04-06 16:23 UTC, kevin-hausmann commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +A.V.E Eigenbetrieb Kreis Paderborn Deponie Alte Schanze|J_Waste|06-05-700-0148396||8.66556757513202|51.7041077540658||||||||||||||
Example for a point source where the stack height class is empty, we need to make sure that we assign a value to each point source!

2021-04-06 16:24 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "        chimney_mapping[line[0]]= line[4]#set to three for height class set to 4 for meters\n",
```suggestion
    "        chimney_mapping[line[0]]= line[3] # set to 3 for height class or set to 4 for meters\n",
```

2021-04-06 16:26 UTC, kevin-hausmann commented on data/gnfr_mapping.csv
> +1.b;Installations for gasification and liquefaction;B_Industry;;;;
See line 3 at the end: ";;;;" instead of the mapping needed

2021-04-06 16:27 UTC, kevin-hausmann commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +A.V.E Eigenbetrieb Kreis Paderborn Deponie Alte Schanze|J_Waste|06-05-700-0148396||8.66556757513202|51.7041077540658||||||||||||||
See line 8: || instead of |<height class>|

2021-04-16 10:06 UTC, AnnaZagorski commented
Then we also wait here for the revised version

2021-04-18 19:33 UTC, Christian-Mielke commented
Please only merge chimney directly with main as it also contains the changes from shapefile already.

2021-04-21 10:45 UTC, AnnaZagorski reviewed
same with as discussed earlier, geopandas does not load easily, but everything else is ok!

2021-04-21 11:13 UTC, AnnaZagorski approved these changes

2021-04-22 08:07 UTC, kevin-hausmann requested changes
Sorry Christian, but we cannot merge the pull request in this form. It duplicates the changes already made in the other PR. This PR should be solely about stack height and should not include anything on shapefiles etc. If you need help on how exactly to fix this, let me know!

2021-04-22 10:41 UTC, Christian-Mielke commented
Okay I will do a hard reset to the first commit in the branch, then push that to the remote to revert chimney to initial state. Then do the rebase of the branch to the main. Then I will reapply only the chimney height related changes and do the final push.

2021-04-22 11:25 UTC, kevin-hausmann commented
Yes, sounds good. As I said, we can do it together if there is the need...

2021-04-22 12:01 UTC, Christian-Mielke commented
Alright I will give you a shout if I need help.

2021-04-22 16:40 UTC, Christian-Mielke commented
Alright I did as I described above, please have a look and tell me if its ok now

2021-04-23 05:42 UTC, kevin-hausmann approved these changes
Okay, I added one more commit, mainly because the mapping file was broken with missing ';' and I added a test to the notebook to find if the mapping actually works for all point sources. Please merge!

2021-04-23 05:44 UTC, kevin-hausmann commented
Dear @Christian-Mielke, I think this is only a first step, as it does not include any specific point source stack heights. We discusses earlier, that the report contains much more information and we should definitively use that as well. Please continue to work on that and present an update as an additional PR - thanks!

2021-04-23 06:16 UTC, merged