added a single file for an individual remapping of differing chimney …
UBA-DE-Emissionsituation/eprtr2lps pull request #25
Opened 2021-04-28 16:18 UTC by Christian-Mielke

…heights from the report added for individual chimney mapping of differing units

2021-04-29 06:15 UTC, kevin-hausmann requested changes
Hey @Christian-Mielke , this is a great start! I added a few comments and suggestions that I would like to see addressed before merging this. Also, please note that you again included the unrelated .dbf file, which should not be here. Let me know if you need help!

2021-04-29 06:15 UTC, kevin-hausmann commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +Gemeinschaftskraftwerk Kiel GmbH GKK|A_PublicPower|01-50-02000283604|A_PublicPower|10.1769762658324|54.3386527337962||||||||||||||
This does not seem right, it should put a stack height here, not a GNFR code

2021-04-29 06:15 UTC, kevin-hausmann commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +Kraftwerk Fenne|A_PublicPower|06-10-00101000|A_PublicPower|6.87899863647934|49.2491320648219|0.712||0.482|||||||||||
Same here: This does not seem right, it should put a stack height here, not a GNFR code

2021-04-29 06:15 UTC, kevin-hausmann commented on data/gnfr_singlestackmap_final.csv
> +name;gnfr;sector;class;available in gnfr;Anzahl
Two minor points:
1. What is "available in gnfr"?
2. Please do not switch to German "Anzahl"

2021-04-29 06:15 UTC, kevin-hausmann commented on data/gnfr_singlestackmap_final.csv
> +Jänschwalde;1.c;A_PublicPower;3;y;1
Wouldn't it be better to use ePRTR-IDs to find the point sources to update? Using the names can easily go wrong on the next dataset...

2021-04-29 06:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +   "version": "3.8.5"
Please revert.

2021-04-29 06:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "chimney_mapping_inidv={}\n",
```suggestion
    "stack_mapping_indiv={}\n",
```
I think this is what you mean? Please use "stack", chimney is for homes.

2021-04-29 06:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "        idx=(data['PRTR activity']==line[1])&(data['LPS'].str.contains(line[0]))\n",
Sorry to be pedantic, but to make this work for everybody, we need to follow some PEP8 (applies to the complete cell):
```suggestion
    "        idx = (data['PRTR activity'] == line[1]) & (data['LPS'].str.contains(line[0]))\n",
```
Are all those brackets () really needed?
Please review your code and try to make it as simple and readable as humanly possible - thanks!

2021-04-29 09:22 UTC, Christian-Mielke commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +Gemeinschaftskraftwerk Kiel GmbH GKK|A_PublicPower|01-50-02000283604|A_PublicPower|10.1769762658324|54.3386527337962||||||||||||||
Yes found the error

2021-04-29 09:23 UTC, Christian-Mielke commented on output/Convert ePRTR data to CLRTAP LPS.csv
> +Kraftwerk Fenne|A_PublicPower|06-10-00101000|A_PublicPower|6.87899863647934|49.2491320648219|0.712||0.482|||||||||||
Yes Kiel and Fenne were mixed up in the table

2021-04-29 09:23 UTC, Christian-Mielke commented on data/gnfr_singlestackmap_final.csv
> +name;gnfr;sector;class;available in gnfr;Anzahl
also changed

2021-04-29 09:31 UTC, Christian-Mielke commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "        idx=(data['PRTR activity']==line[1])&(data['LPS'].str.contains(line[0]))\n",
Without brackets I get a data type error because a bool and and int array are combined. With brackets everything works fine so I would leave them in.

2021-04-29 09:39 UTC, Christian-Mielke commented on data/gnfr_singlestackmap_final.csv
> +Jänschwalde;1.c;A_PublicPower;3;y;1
I think this is okay as I filter for both the 1.c (Public Powerstation) and the Location (Jänschwalde)

2021-04-30 06:59 UTC, kevin-hausmann approved these changes
I think this is will do.

2021-04-30 08:10 UTC, AnnaZagorski approved these changes

2021-05-03 11:37 UTC, merged