added kriging to rastergrid of pointdata from shapefile using pykrige
UBA-DE-Emissionsituation/eprtr2lps pull request #27
Opened 2021-05-30 21:43 UTC by Christian-Mielke

This is handy for generating raster grids to be compared in a GIS with e.g. TROPOMI raster data later on.
You need to have GDAL and pykrige installed to make it work.

2021-06-01 09:52 UTC, kevin-hausmann requested changes
Hi there, unfortunately there are a couple of issues with this PR, including:
- The purpose of this whole endeavour is not clearly explained
- Deletes a bunch of unrelated files (incl. the result.csv)
- Add a local .gitignore instead of using the global one
- There is no documentation on this classes and methods
- There are no unit tests
- There is German/English language mixing
- Use of classes is unneeded as there is no internal state
- Class names such as "Rasterfun" are non-descriptive

I also put some more comments inline below, but stopped as those would be too many. Sorry, be this needs reworking. I'd be happy to help you with this, we can surely find the time to do some pair programming...

2021-06-01 09:52 UTC, kevin-hausmann commented on pyscript/shape2raster.py
> +#  class for writing raster data
Please use docstrings instead

2021-06-01 09:52 UTC, kevin-hausmann commented on pyscript/shape2raster.py
> +    def __init__(self):
This is not needed

2021-06-01 09:52 UTC, kevin-hausmann commented on pyscript/shape2raster.py
> +class Rasterfun(object):
No need to inherit from object, this is fine (besides the class name)
```suggestion
class Rasterfun:
```

2021-06-01 09:52 UTC, kevin-hausmann commented on pyscript/shape2raster.py
> +    def schreibebsqsingle(numpyarray: numpy.ndarray, out: str):
Needs to be static or have parameter `self`, see all the above.

2021-06-01 12:05 UTC, AnnaZagorski commented
then I will add my review after the rework

2021-08-24 07:41 UTC, kevin-hausmann commented
@Christian-Mielke Will you still be working on this? Is this still relevant? Otherwise, please remove and delete the branch, thanks!

2021-10-01 05:59 UTC, closed without merging