Make sure LPS are sorted by name ignoring case #30
UBA-DE-Emissionsituation/eprtr2lps pull request #32
Opened 2021-08-23 20:18 UTC by AnnaZagorski

Fixed the problem with lower cases which were at the bottom unexpectedly…Now the LPS are sorted alphabetically.

2021-08-23 20:21 UTC, AnnaZagorski commented
please give me feedback if the sorting is ok.

2021-08-24 07:38 UTC, kevin-hausmann requested changes
Great, that seems like the correct solution! I added one suggestion (feel free to drop it, if you disagree) and I request the removal of the non-topical changes. Thanks!

2021-08-24 07:38 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "ORDER BY name COLLATE NOCASE"
This is a good solution! Maybe we would also state explicitly that we want a->z instead of relying on the default?

```suggestion
    "ORDER BY name COLLATE NOCASE DESC"
```

2021-08-24 07:38 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +   "version": "3.8.10"
Please do not commit these kind of changes, thanks!

2021-08-24 07:38 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +  "toc": {
Same here, the "toc" section should not be part of this commit. In general, you need to review your changes to all staged files before creating the commit. If you spot changes that are unrelated to what you are trying to achieve (like this one), please revert those selectively, leaving only the topical changes in place. Let me know if you need help...

2021-09-30 10:03 UTC, kevin-hausmann approved these changes

2021-09-30 10:04 UTC, merged