Most concise sql query
UBA-DE-Emissionsituation/eprtr2lps pull request #8
Opened 2021-03-04 13:26 UTC by AnnaZagorski

2021-03-04 14:16 UTC, kevin-hausmann requested changes

2021-03-04 14:16 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "conn = sql3.connect('../data/prtr_en.db')"
Why did you add the ../ here? This breaks the workbook for me. Should be:
```suggestion
    "conn = sql3.connect('data/prtr_en.db')"
```

2021-03-04 14:16 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "data.to_csv('../output/Convert ePRTR data to CLRTAP LPS.csv', index=False)"
Same here:
```suggestion
    "data.to_csv('output/Convert ePRTR data to CLRTAP LPS.csv', index=False)"
```

2021-03-04 14:24 UTC, kevin-hausmann commented
You should also close the db connection directly after reading into the data frame, because it might otherwise remain open if something goes wrong while running the rest of the workbook, I think

2021-03-04 14:30 UTC, kevin-hausmann submitted a review, later dismissed

2021-03-05 05:15 UTC, kevin-hausmann requested changes

2021-03-05 05:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "WHERE a.year = '2015' AND r.compartment = 'Air' AND a.main_activity = 1\n",
It seems much more logical to me, if we apply the year filter to the facility rather than the activities, what do you think?
It does not make a real difference for the results, I guess, but I feel it is much more intuitive.

```suggestion
    "WHERE f.year = '2015' AND r.compartment = 'Air' AND a.main_activity = 1\n",
```

2021-03-05 05:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
>      "conn = sql3.connect('data/prtr_en.db')"
We should open the connection, make the query and then close the connection inside one cell of the workbook. That way, the connection cannot leak and remain unclosed.

2021-03-05 05:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "data.head(10).fillna(\"\")"
Is this what you intend to do? The fillna() will not survive beyond this cell and will only be applied to the first ten rows!

```suggestion
    "data = data..fillna(\"\")"
    "data.head(10)"
```
or
```suggestion
    "data = data..fillna(\"\", inplace=True).head(10)"
```

2021-03-05 05:15 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "SELECT f.name AS LPS, a.business_sector AS GNFR, \n",
Please add the prtr_key as an extra column, we need that later!

```suggestion
    "SELECT f.name AS LPS, a.prtr_key AS PRTR, a.business_sector AS GNFR, \n",
```

2021-03-08 15:05 UTC, AnnaZagorski commented on Convert ePRTR data to CLRTAP LPS.ipynb
>      "conn = sql3.connect('data/prtr_en.db')"
yes, ok, that's true.

2021-03-08 15:06 UTC, AnnaZagorski reviewed
the requested changes are very good!

2021-03-08 15:16 UTC, AnnaZagorski reviewed
oh yes, we also need a.prtr_key

2021-03-08 18:58 UTC, kevin-hausmann commented on Convert ePRTR data to CLRTAP LPS.ipynb
>      "conn = sql3.connect('data/prtr_en.db')"
If you agree, please change the code accordingly. Right now, connection creation, usage and closure are still in three seperate cells...

2021-03-08 18:59 UTC, kevin-hausmann commented
With all these changes, the workbook is no longer functional for me. I get a render exception, please fix.

2021-03-08 20:34 UTC, AnnaZagorski commented on Convert ePRTR data to CLRTAP LPS.ipynb
> +    "data.head(10).fillna(\"\")"
I splitted the data.head(10) and the data.fillna("") in my new commit

2021-03-08 20:36 UTC, AnnaZagorski commented
because the notebook was not functional anymore, I pushed a new notebook file

2021-03-10 13:24 UTC, closed without merging

2021-03-10 13:26 UTC, AnnaZagorski commented
this pull-request is closed now, a new one will be opened